version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgresdb_container
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d/
    networks:
      - my_network

networks:
  my_network: